### ISSUE TITLE
Pod "ibm-operator-catalog-*" in status "CrashLoopBackOff" because of "Error: open db-792922255: permission denied"

### ISSUE THREAD

**Issue by mbecker** [IBM/cloud-pak#475]
Hi,

trying to install the IBM Operator Catalog results in pod(s) with status "CrashLoopBackOff". The logs of the pod(s) and the last status is as follows:

```sh
Error: open db-792922255: permission denied
Usage:
   [flags]

Flags:
  -d, --database string          relative path to sqlite db (default "bundles.db")
  -h, --help                     help for this command
  -p, --port string              port number to serve on (default "50051")
      --skip-migrate             do  not attempt to migrate to the latest db revision when starting
  -t, --termination-log string   path to a container termination log file (default "/dev/termination-log")

time="2021-01-15T11:13:07Z" level=panic msg="open db-792922255: permission denied"
panic: (*logrus.Entry) (0x1115c40,0xc00025f960)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000b4000, 0xc0002a2b40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/src/vendor/github.com/sirupsen/logrus/entry.go:239 +0x2da
github.com/sirupsen/logrus.(*Entry).Log(0xc00025f880, 0xc000000000, 0xc000145f68, 0x1, 0x1)
	/src/vendor/github.com/sirupsen/logrus/entry.go:268 +0xeb
github.com/sirupsen/logrus.(*Logger).Log(0xc0000b4000, 0x0, 0xc000145f68, 0x1, 0x1)
	/src/vendor/github.com/sirupsen/logrus/logger.go:192 +0x7d
github.com/sirupsen/logrus.(*Logger).Panic(...)
	/src/vendor/github.com/sirupsen/logrus/logger.go:233
github.com/sirupsen/logrus.Panic(...)
	/src/vendor/github.com/sirupsen/logrus/exported.go:129
main.main()
	/src/cmd/registry-server/main.go:52 +0xbe
```

The IBM Operator Catalog is installed as described here with the manual YAML files: https://www.ibm.com/support/knowledgecenter/en/SSGT7J_20.4/install/install_online_catalog_sources.html

Please advise how to fix that issue.

**Comment by cdjohnson** [comment]
@mbecker This is likely happening because the pod is running with a restricted SecurityContextConstraint somehow.

Can you make sure that you created the CatalogSource in the `openshift-marketplace` namespace?  That namespace is created by Openshift and has the `anyuid` SCC associated with it.

When you describe the pod, it should look something like this and have the `openshift.io/scc: anyuid` annotation set:
```
> oc describe po ibm-operator-catalog-rdbsf -n openshift-marketplace

Name:         ibm-operator-catalog-rdbsf
Namespace:    openshift-marketplace
Priority:     0
Node:         ip-10-0-174-26.ec2.internal/10.0.174.26
Start Time:   Mon, 11 Jan 2021 10:45:38 -0600
Labels:       olm.catalogSource=ibm-operator-catalog
Annotations:  k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "",
                    "interface": "eth0",
                    "ips": [
                        "10.129.2.16"
                    ],
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "",
                    "interface": "eth0",
                    "ips": [
                        "10.129.2.16"
                    ],
                    "default": true,
                    "dns": {}
                }]
              openshift.io/scc: anyuid
Status:       Running
IP:           10.129.2.16
IPs:
  IP:  10.129.2.16
Containers:
  registry-server:
    Container ID:   cri-o://eafc27ae3ac82cd5e2ba6ae7eb91d3dfc931db97a3b602062d4f8871e7ace703
    Image:          docker.io/ibmcom/ibm-operator-catalog:latest
    Image ID:       docker.io/ibmcom/ibm-operator-catalog@sha256:4a35a59e2deb0f450190d16399fd83863631970652b12db85356bac605c5fc2d
    Port:           50051/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 11 Jan 2021 10:57:50 -0600
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 11 Jan 2021 10:55:42 -0600
      Finished:     Mon, 11 Jan 2021 10:57:44 -0600
    Ready:          True
    Restart Count:  2
    Requests:
      cpu:        10m
      memory:     50Mi
    Liveness:     exec [grpc_health_probe -addr=:50051] delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:    exec [grpc_health_probe -addr=:50051] delay=5s timeout=5s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-vs2wv (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-vs2wv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-vs2wv
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
```
